# Generated by Django 2.2.16 on 2021-08-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210817_2102'),
        ('reviews', '0002_auto_20210817_2117'),
    ]

    operations = [
    ]
