# Generated by Django 2.2.16 on 2021-08-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_merge_20210818_1440'),
        ('reviews', '0004_title_rating'),
    ]

    operations = [
    ]
