# Generated by Django 2.2.16 on 2021-08-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_merge_20210818_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
